language: java
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ci@estimator.cloud
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- export BUILD_NAME=configuration-server-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
install: true
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
  - secure: sbnrAAqeO2sfBwSl4a/1sJPVjFpVFDhwDURo7v7lMybeXsec8U/kOBXeY4dLIEAviM8icssJpqxXKgZVzicdl4mPeCCtCtXXASmmi8MP9TOJYBul58mti+UJRToeW0feR49zh8AOrwp3JreLExR39w5gIZD4Bkh33VKd28TyXxDgJzjoWkek1qDA4NpxTQltjGRZyJHvp54BPcHv9HaXE0pzZFN7g0P7hhcd0zROGfSZQMMk9Emo6QyBNgWB8sEbkwrffF95mSZMAeLBWKZc7VNstjwfTnsj9lfZZzNwBPlN33beeus0lrD4/xyD3NhjbJ65hzeY2JiNnjzw1JmT5PwqHdpCbhL9A20aOsDLw12aIqEeCLv1AKovG0KqYe92EEOLtfXRYL1YAPtT968TcfKEJZ4l4kPtvSfUv1zRKkG15Nct1ua7/gWyQyjtxrOzbx8n4YZhDzfTItWjm85w3eiiLdPfBGMfquMqhe8t4tBxVfngeePtK7ZW3Occ9oek415cOzE7dE3wk+As8o/tcns3EHejLPVTEsCg3feqAu4EfB6wJcAvc8c8/5Sihgw8X9FJxCvR7AuY7JZSzpKhlJInYAphp4D2V5nNv5SAUfaHtSVNXkl2xQPBZsOMG/28/3IA94v313a03ACF9Tl8paoM36IjU91ZovgqKJKVlgs=
  - secure: hqQI+Ph+k+NKq7VkzfafwfaWRkmV6+afRx1yI6mCLoV0+ZTttOsdBXji60rY77pGF4Xux1WFTSPkwcfC9po193F9mZGoHZUtX0fUXlNQTj43BYhDZI2ILlsniD17g6k4DjvuT8TjeHv0ThS11V+5f84RrbRbEsHxwg/aeux0kkzETLJTALax+ghklizt0WvkFAKcbUJOU7o0RHQkb0SIUiEZRtykoH2ZbFMwx10RIjIt56ZsdZtXPl3dle3qqa5+qPYLl0S6GcmR6zJqQswaV2m2mh4s2WYkm3E/+Ozm2yYOEQRppIjr//Ow0Vh4BFOVMjmvII5paO/hCSGSwr5caGq9I2mXhQ54IiF7WkCL+QtM7ZqwzuIR0WwIY5Pk0K6opKRBF6okvB4k3/omOZoy1S4OFe+1RR6pQ4WrRgvXna3GMpdzjq+JNS1ZKgQy3LvTwRmiX4JHZQsLp/Kn7JrCHTHdmzHk5xstul4iL93fPo/jScqPhOMr/tVBmKZu8WKNvcu6/qt1Yu6G73JH3ejoPRh99xrUpc8zyqHPgSSOWQfthJSq3uQgnz2BdLkfhqxtnDp/qWZ878SDOWOfaD1dOs2XrrA9R+7GKWG74VI9LBHOlD8b4S9kf8LelgeOsIT0DehBfFejF3atI6N+n04+gDKvCyfbO36seNk/KseQ8WE=
  - secure: UFAukdy41M2sQtX7TAIpPDrM1ss2BOK//X9QwPVB8Z1/EVS/8/k4N+K9MhBRLce97YdUzyykluzWTw7BRC1JbqqdrOWjcKYeZY6KD5OSxvV5cswN8Jg04fohXhFbuPSHMDzoTIsSegxHHbOrfQhqnDexQpYBxjk9jzuv4gvXUQMiaYqlIp5w6bAZs4zAnVSgv152FHczWmCu1OXzI5kaPRD4dpRYoD8QZiiq94UKP5ThlF7NeCIw0KREUxyx3oL2d6qj2vGZecmA7tjjyRRu80ejaxvrFL/BRnhlU9Um8EEBokH7mIjNDE9a2hHsGApj/SaPxqxUnGJY7BctbHcoJSIXGELRy0mwPVzviFfiEVgb+qM4OEb9P2JFHdOb1Kb2s4QyCKHih/YzfNlNeHPqJeiu1gYdCwJmEjmsARX6mPKO0/VfrwL4fJzytViW9Ei7dpEkCdeqfWMU+y7nwnuFbrPintA07wZvfXDRsE4uFKpA/47RHZyJkvJ6mxvQjHfm78enahxjInGMqdUk0ND5px3gS3PHWvvPi+THh8oxhMyxNIU8ke86pNyMx/YRfpNyCx+jK0Oq65CF2itx81VBcmTZUq8EpkfUPINEg4YolfTrLweaLQQP0NCQAKYcNWh5A+rQhj2n8fStLm7l9GmyAQ99eBoJGOw0A7ZI22YJ1n4=
