language: java
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ci@estimator.cloud
  on_success: always
  on_failure: always
branches:
  only:
  - master
install: true
script: ./mvnw clean package dockerfile:build
