language: java
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ci@estimator.cloud
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: lnwHv1AGaoAzeUw0qjpgxESLwjUaqn6LHkibp350fKHmPxsQpDC42wyz3vt3R/APMyRFmsvAlx0wb2NurSOU8UDdGkEZsX1c7UmKFKeiJY9Fuq+ax+778zl9+7dS0SwsanfiZS/NbfOm4U2xyi6iMBPJw+yfMvZ6BD3PGSO+WU7OdRd5NLgNTDkhXrYph9l7yfcp9OTdyG9tMEU4MKUpP3cwNWrfMn113QTe16955XRTjTKOFvqpOj8YxYA3ggfrNUVxzZiknZDpnpDMNa8eHxqblAdbY777bgYSmdI4Ur+0Ht5XDu13RZyoM3JJzkrbpuqHusOuwugxOSef+Wft6TS/1PCL/WPUqQKqMFUFkr/yypE2kkBYmChsw36Sl/n9vgqXFXgLRaPFXE9dxPsP9Cm0sCQOAxZjpNVfMKoyUoNhpYi5syJqOz87mJRs5xWnK6zvoyW5Y2rykQJdl4tGbjEDN722c1l03oiIJMjTLoTRQp8mH+4N8UduE33YyZrj8jz48uwfEz1oSSKgF/vVU0h7ZH77MEEn51fPz5yosgR43rZKndhof4C9XOud8nPlNRIZWDQNBcZ7750TVfPzTV1Si+l72L1abRDGJi2EOA7vgdKh0Psz1RqU9JXudk+ilSyjgwqKHZ7MVh76zGriUMrbHUtooOVLl25zrwUzaZo=
  - secure: cSGem4arLdiRrLtgZGUTQYCXI0Sj/cJcmdOcd7um2/Z/E7ugh/+OvuUwLWzQba0YDYAMe7d10mBW7Tr2CwMKHHEmYe9t1JJFD+T5oJxiAgnbKMrWpop5haJd2VaanjSzNpM2QkG2eksCzW6HuDaqnS4MpisKNIq4kPCz/SZS1ElritiKZ6BoEl53+tsSPONOjFUtGDl0UztAZ+yKNWPROFRnLqUeiO07UpVALPM4hIg/RYMqUTR3UN+3VyAemYdBzspXGQqIYrXO9unD+wADKFLQdRRAS3yX5pXPYM0ZWHmKX0G29mD6ajL78e8ngkDrpDQ3QzXaAfHkw1fDsYycQAAu3AkXEP1P/CDpNVLDI26VkRLV4O/WgA/IdHrOEZ2Zl7CFU96XtPsFwpxDAW5glpowfGD+vYAawozkSPpsBR3fooT88wYqWE8q7VMXRt9b35epgt28u5qZxAc+ia6aNWf+bzUYF9zKnkpo4IBK1XtPtolajjfV3nIcAw84Fp59qAEdAu6AbXpIFc2mKidXJdhe1LIwGSszQhlzY+Y1Q5Pu8BjxvR6TDd0HBDToTniLEd8Jlfj6/ig+Z8EHr2mLUoRTrfaJTSRWRhZUNPEpM2B+/nn6HFMTl+5VzDtq5KquMSnXgd6tcaF8+KpRqNiSXkDmyNTPDqjr7rCsTJDmOmE=
  - secure: d1j1cnmbOjzmIoOb4916KGMuePcBY0ATiylvGFlWqZ53XwMVUqGFSueHQ7kmJPRbhK9FLBSQ2Vu9GDECxp/qRfFtnQVHIuFjPOJDpV/AnM+b23T+AjRcxJfugt8MdV+3FpgvSG9l3mw1uLp9hEx3WgqfnF47xFynWWYiHE4HQccoSjBB0iWUYrU1XZkjPbq3ZIghJDf5SMBnOAf2uGuGsiuC1ql9H9LpizONf28YjCELPsVdVURCVdtIoF4v9dGZU+HP5W3Fo/xDZwpff3Co1PfJOWnyNwfakrxMXRW0ot0Toyb2rLbobpzxBTC9N6t/CwgsRJq6ZFRuBb6wPYaLK81jod+nfb+kH077C7opbPcPlV8HI4P3yzQslVmjTyx2I43Keozq8APNiCTeKo8wIz32jwy9/tS/DaIVAxAOQ8AT+EMTxjqUl06TkkNknDb7WNpsTTN4sCh58IGff9+B0SmKzhZivwTJ9w5UUdf+zv/yGl/qYgFuD+EI3HOkz6q2Ykp84IJSu3Mmv+RtkpAEd1EEeKqHCQ9Sql4KiR4HWYHPpxJV9y3l+2/VnmocYeXKYxcGCYjjfMDco7qAJgtKlx6hQQ5l0qRqx1q/CcXWxhBVQVjysFBX2qpyHiKffvDVM73GlovPvBJlysDUhT8TwJXTJs7/xf1mU2bJ4d8cZVA=
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- export BUILD_NAME=configuration-server-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
install: true
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh