language: java
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ci@estimator.cloud
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- export BUILD_NAME=configuration-server-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
  - secure: fTfQNLCVa+KTMhzJRmw5mjOlm0TBljo54sRc5ZGbM3Bh93MbSEWl+L8CCS7FRAShcb3gyg2LuyYK5Tov2dTzQ1mnf+EdyZaeMMatO0D5GOa6VybD+5Ru7hrkpaMHVpPZLpU7ZiZyns8x2R55xnhrAZQahlzqvE3A3vVfDPbQ3lfSBa+fivz1AtpzQ6sCld3XJ9reDtRDxQyFsIop3qyHV0AUNhubjGvm9ZSPfz5ARS4p2dprGRjxSKvOzX9JFXNTluk5RWRtkt6c+xu1IkwGt39vGdGcEG0sxrHdURLNYGjrjylbbRu8enrphVsSe2Ayv0LiFZrw5eeWnnBNWMk0pHfX0X5MvIvjaWwQbzkp6u4STKyIhaUm8bQxNpNJn5UZJ81h2k0cJY4uWz4KkKmsjWmulZ0kUQy6sRXIR8+5Ako6vL5hT4waZN+vE8+ozcO3aZq+xjlT1RRtT94pY6a82k18bhRyN+IiL9xfPD65wQpWSQ9nIadHB/ctYx82CeJeVVV5GwkmxgNOGi8juHrISo6hg0li+TbgPHEquKV7XhH+F8VGiTILA0IuZC+LPg98D8bZP8JBYBcFthI/LuS8DPH+knrD+7hdSafUIVSDj1dMIk6v7mQhaAp2z2FMsIYkCoYwA+XYddqZPC+F94CBIQywoo3LI0Rf1K7yJfkwIxI=
  - secure: JTM0E54XORq/cma6N1FCtQ9W7gLWuiS+gUI0aUga14itSLIWGIx5XbcmhP331dV3pQoUfuIjyZg1lSLi9mwaF8qOY9BJ2AWIgw17v0ww1vmF7V9+zl6UxB25jRll7BD8uLv5bXWfA/mTXfeQpgKsGx5jIAt3HSoxcDXcWDbmjoUvJvk2aJ1WzrewQaB+UFfOycaziDfhkxJUJCt2rqd/B3Lr5fVTvkiNUt6sDu/2DTzNCesKZOvCEj2cgAG4m4qyhQEVKcsptE+0UJ1a6D0pJ5yzXSCtHywW+OEGYM9mHjQiZaxYARnjMexLpaUxO8RX7pTWSP6jo4Pi/teOn+Bj8RtgmA4URLAXgJdhNJmOvT3NcKPke/mjspmXhc5i5hupNw1xwTR2S13wtaSZgb8MopuWihC6elp7Wr7usig/mxZdhlLQ54x3lpvAvj7n8fHh9W6QUSh+SF6uiAGppWPFNBD8e6RN7KrgouCj69wtwvRjjs+cDiWcBNl3L8vR8+qKANHpkjmWDcCf/E8vvsyzA5ZpXh9bI05Y0uVjlgrRZuaQP/FzYO/NyMQz6IL5UW+9SqFAqbpFlN96/Z1kmUuiYlDsEbGE7Cg1+mK9k1jA6hacnoDX2QBN4dZZAA7wlP7xF+Nmf2EC5A0ddB7v0my0fcsGJL/jmNielgT97DQQQTY=
  - secure: XLceMA0yYnWk0wv5PkDmELshmTH8x4AJCzug/QCPvbaQseDDsy58hV8WajUbCM1NQtwBHI9c6yFVF3jkNJkGPTlyHNo4Cls16S00wvq9bEyxL8SvfqVvHY+H0km6Jzq1bjIe7fh42suryq4Qc49iopEIWkJGkzYE3fA40sXLsOI+qU7IqYzDbhFLUBVuwg9uGll//+LMn6fGr3yK8qOuojW5MJ6kdH3PEgZ+p7MWaNeiG4w6p525XY7qSiaKX29A+r0oonpz+9hEsPoDEB0MeVyf7aE/bq/lst6pQv5Cs1VNA4ebuZodPs3J05EqLwdBE4XUsgeoxdqFye52neVZTavoaQyT7F5dWm4Gu5MG4RSqzEWbWeCrFb+hv0OGr9KrUExfeEcKEqIZt+1L92Y2E+JQusPHJy53+UOHyVL+OCCaJDFYWxvnJJ8YowAzS24P1OTmph41J+2yTo0aeU4w2Y9vdkyIZ8Fqswa8TGoBVQuczgsMW3cibr6VUk34hHoVSEcJAIMRAv+mk0AcyUsY1JeyL07d/iE2i/ACdxjMqQKmz2aI72sJ9IPT7fIwtBfDutVghBo6FbBO8XUBkMfqYWHya/tu1le6t7U/Hn9Li0lq/QpUSEd+VofFMn+oHMsgy5PXJOmuooPlFDVIl/GtT+7FaUC1hfC2Gxm8LbsTato=
