version: '2'
services:
  configuration-server:
    image: cloudestimator/configuration-server:${BUILD_NAME}
    mem_limit: 1000000000
    ports:
       - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://internal-cloud-estimator-lb-1078220646.us-west-2.elb.amazonaws.com:8761/eureka/"