version: '2'
services:
  configuration-server:
    image: cloudestimator/configuration-server:${BUILD_NAME}
    mem_limit: 1000000000
    ports:
       - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://ip-172-31-5-46.us-west-2.compute.internal:8761/eureka/"