server:
  port: 8888
  
spring:
  application.name: configuration-server
  output.ansi.enabled: always # Show colored output
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/cloud-estimator/configuration-repo
          searchPaths: organization-service, project-service
          username: # -Dspring.cloud.config.server.git.username
          password: # -Dspring.cloud.config.server.git.password
