server:
  port: 8888

spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/carnellj/config-repo/
          searchPaths: licensingservice,organizationservice,specialroutesservice,zuulservice,authenticationservice
          username: native-cloud-apps
          password: 0ffended